# Generated by Django 5.2.17 on 2026-09-22 22:31

import wxcloudrun.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_date', models.DateField(primary_key=True, serialize=False, verbose_name='日报日期')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='一句话综述')),
                ('html', wxcloudrun.models.MediumTextField(verbose_name='日报 HTML')),
                ('byte_size', models.PositiveIntegerField(default=0, verbose_name='UTF-8 字节数')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='内容指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'db_table': 'reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
